spring:
  profiles:
    active: @profile.name@
  application:
    name: cloud-gateway
  # 若不使用redis需要注释掉此类信息
  redis:
    database: @redis.database@
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  type-aliases-package: com.hcframe.**.entity
  configuration:
    # 开启Sql日志记录
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
