server:
  port: 8080
  servlet:
    context-path: /es
spring:
  cache:
    # redis缓存
    #    type: redis
    #    redis:
    #      time-to-live: 1d
    #      use-key-prefix: true
    #      cache-null-values: true
    #      key-prefix: cache.
    # ehcache缓存
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  application:
    name: cloud-elasticsearch
  elasticsearch:
    rest:
      # es 地址，如果有多个地址，则逗号隔开
      uris: http://192.168.4.119:9200
      # 若有用户名密码，在此设置，
      username: elastic
      password: Y2l70uQ7l3Lu9n2tSIn1Bq39
  # 若不使用redis需要注释掉此类信息
  redis:
    database: 0
    host: 192.168.100.145
    port: 6379
    password: root
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://192.168.100.145:3306/common?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://127.0.0.1:3306/common?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用Druid数据源
    initialSize: 5
    # 初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  type-aliases-package: com.common.common.entity
logging:
  level:
    com.common.common.dao : debug
# 是否开启redis 用户登录，若开启此项，需要配置redis节点及相关配置，若不开启，需要注释掉redis相关配置信息
isRedisLogin: false
# 用户登陆超时设置，单位为小时，此值不能为0
login-time-out: 4
# swagger配置
swagger:
  # 配置controller包路径
  path: com.common.common.controller
  # 是否开启权限
  enableAuth: false
  # 用户名
  username: admin
  # 密码
  password: admin
# Druid连接配置
druid:
  # Druid用户名
  username: test
  # Druid密码
  password: test
  # Druid 允许访问的IP,默认全部允许
  #  allow: 127.0.0.1
  # Druid 拒绝访问的IP,默认不拒绝全部
#  deny: 10.0.0.2
# 是否开启controller日志监控
show-controller-log: false
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@192.168.4.119:8080/eureka/


